# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table category (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  version                       bigint not null,
  creation_date                 timestamp not null,
  modification_date             timestamp not null,
  constraint pk_category primary key (id)
);

create table ingredient (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  version                       bigint not null,
  creation_date                 timestamp not null,
  modification_date             timestamp not null,
  constraint pk_ingredient primary key (id)
);

create table recipe (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  type_id                       bigint,
  time                          integer,
  description                   varchar(255),
  version                       bigint not null,
  creation_date                 timestamp not null,
  modification_date             timestamp not null,
  constraint pk_recipe primary key (id)
);

create table recipe_ingredient (
  recipe_id                     bigint not null,
  ingredient_id                 bigint not null,
  constraint pk_recipe_ingredient primary key (recipe_id,ingredient_id)
);

create table recipe_category (
  recipe_id                     bigint not null,
  category_id                   bigint not null,
  constraint pk_recipe_category primary key (recipe_id,category_id)
);

create table type (
  id                            bigint generated by default as identity not null,
  type                          varchar(8),
  version                       bigint not null,
  creation_date                 timestamp not null,
  modification_date             timestamp not null,
  constraint ck_type_type check ( type in ('Desayuno','Comida','Cena')),
  constraint pk_type primary key (id)
);

-- foreign keys and indices
create index ix_recipe_type_id on recipe (type_id);
alter table recipe add constraint fk_recipe_type_id foreign key (type_id) references type (id) on delete restrict on update restrict;

create index ix_recipe_ingredient_recipe on recipe_ingredient (recipe_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_recipe foreign key (recipe_id) references recipe (id) on delete restrict on update restrict;

create index ix_recipe_ingredient_ingredient on recipe_ingredient (ingredient_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_ingredient foreign key (ingredient_id) references ingredient (id) on delete restrict on update restrict;

create index ix_recipe_category_recipe on recipe_category (recipe_id);
alter table recipe_category add constraint fk_recipe_category_recipe foreign key (recipe_id) references recipe (id) on delete restrict on update restrict;

create index ix_recipe_category_category on recipe_category (category_id);
alter table recipe_category add constraint fk_recipe_category_category foreign key (category_id) references category (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table recipe drop constraint if exists fk_recipe_type_id;
drop index if exists ix_recipe_type_id;

alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_recipe;
drop index if exists ix_recipe_ingredient_recipe;

alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_ingredient;
drop index if exists ix_recipe_ingredient_ingredient;

alter table recipe_category drop constraint if exists fk_recipe_category_recipe;
drop index if exists ix_recipe_category_recipe;

alter table recipe_category drop constraint if exists fk_recipe_category_category;
drop index if exists ix_recipe_category_category;

-- drop all
drop table if exists category;

drop table if exists ingredient;

drop table if exists recipe;

drop table if exists recipe_ingredient;

drop table if exists recipe_category;

drop table if exists type;

